#!/bin/bash

# Prompt colors
_HOSTNAME_FG=$GRUVBOX_BG
_HOSTNAME_BG=$GRUVBOX_BORANGE
_PWD_FG=$GRUVBOX_BG
_PWD_BG=$GRUVBOX_BYELLOW
_GIT_FG=$GRUVBOX_FG2
_GIT_BG=$GRUVBOX_BG2

ARROW=''

##################################
# Helper functions

_arrow() {
    _col $1
    _bg $2
    echo -en $ARROW
}

# Set color (256 color mode)
_fg() {
    tput setaf $1
}

_bg() {
    tput setab $1
}

_col() {
    _fg $1
    _bg $2
}

# Clear color
_clr() {
    tput sgr0
}

_hostname() {
    local host=$(echo $HOSTNAME | cut -d "." -f 1)
    echo -en "$host"
}


##################################
# Prompt

_PS1_HOSTNAME='\[$(_col $_HOSTNAME_FG $_HOSTNAME_BG)\]$(_hostname) \[$(_col $_HOSTNAME_BG $_PWD_BG)\]$ARROW'
_PS1_PWD='\[$(_col $_PWD_FG $_PWD_BG)\] \w \[$(_col $_PWD_BG $_GIT_BG)\]$ARROW'
_PS1_GIT='$(__git_ps1 "\[\033[38;5;${_GIT_FG}m\033[48;5;${_GIT_BG}m\]  %s\[\033[0m\]")\[$(_col $_GIT_BG 0)\]$ARROW'

PS1="${_PS1_HOSTNAME}${_PS1_PWD}${_PS1_GIT}\[$(_clr)\] "
